---
# This is an example playbook to execute Ansible tests.

- name: Verify ceph mon1
  hosts: ceph_osd
  become: true
  gather_facts: false
  tasks:

  - name: Get list of already registered Nodes
    ansible.builtin.command:
      cmd: "ceph orch host ls --format json {{ hostname }}"
    delegate_to: ceph-shell
    register: osd_info
    changed_when: false

  - name: Assert all nodes are registered
    ansible.builtin.assert:
      that:
        - osd_info.stdout != ""
        - osd_info.stdout | from_json | map(attribute='addr') | length == 1
        - osd_info.stdout | from_json | map(attribute='addr') | first == ceph_cluster_network_ip
