---
- name: Get hostname
  ansible.builtin.command: hostname
  changed_when: false

- name: Download cephadm
  ansible.builtin.get_url:
    url: https://github.com/ceph/ceph/raw/pacific/src/cephadm/cephadm
    dest: /usr/local/bin
    mode: 755

- name: Create ceph config dir
  ansible.builtin.file:
    path: /etc/ceph
    mode: 0755
    owner: root
    group: root
    state: directory

# - name: Add repo for ceph pacific release
#   ansible.builtin.command:
#     cmd: cephadm add-repo --release pacific
#     creates: /etc/apt/sources.list.d/ceph.list

- name: Bootstrap ceph cluster
  ansible.builtin.command:
    cmd: >
      cephadm bootstrap
      --mon-ip {{ ansible_default_ipv4.address }}
      --skip-dashboard
      --skip-mon-network
      --skip-monitoring-stack
      --cluster-network {{ ceph_cluster_network }}
    creates: /etc/ceph/ceph.conf
  register: ceph

- name: Output cluster Info
  ansible.builtin.debug:
    msg: ceph.stdout
  changed_when: false

- name: Spawn ceph shell for later use
  community.general.docker_container:
    name: ceph-shell
    image: "quay.io/ceph/ceph@sha256:c5fd9d806c54e5cc9db8efd50363e1edf7af62f101b264dccacb9d6091dcf7aa"
    ipc_mode: host
    network_mode: host
    privileged: true
    interactive: true
    restart_policy: unless-stopped
    tty: true
    volumes:
      - /var/run/ceph/459e1664-366d-11ed-9073-dca63247e962:/var/run/ceph:z
      - /var/log/ceph/459e1664-366d-11ed-9073-dca63247e962:/var/log/ceph:z
      - /var/lib/ceph/459e1664-366d-11ed-9073-dca63247e962/crash:/var/lib/ceph/crash:z
      - /dev:/dev
      - /run/udev:/run/udev
      - /sys:/sys
      - /run/lvm:/run/lvm
      - /run/lock/lvm:/run/lock/lvm
      - /:/rootfs
      - /etc/ceph/ceph.conf:/etc/ceph/ceph.conf:z
      - /etc/ceph/ceph.client.admin.keyring:/etc/ceph/ceph.keyring:z
    entrypoint: bash
  notify: Configure auto add available devices
