---
- name: Prepare
  hosts: raspberries
  become: true
  vars:
    docker_expose_api: true
  roles:
    - role: einfachit.epic.docker

  tasks:
    - name: Configure static IP for wired network
      ansible.builtin.blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          # Set Static IP for wired network interface
          interface eth0
          static ip_address={{ ceph_cluster_network_ip }}/24
      notify:
        - Reboot server
        - Wait 600 seconds, but only start checking after 10 seconds

    - name: Read device information
      ansible.builtin.shell: set -o pipefail && vgs --no-headings --separator ';' | cut -d ';' -f1
      args:
        executable: /usr/bin/bash
      register: vgs
      changed_when: false

    - name: Force remove all volume group with name vg.services
      community.general.lvg:
        vg: "{{ item }}"
        force: true
        state: absent
      loop: "{{ vgs.stdout_lines | map('trim') | list }}"

    - name: Download zram git repo
      ansible.builtin.git:
        repo: "https://github.com/StuartIanNaylor/zram-swap-config"
        dest: /tmp/zram-swap-config
        version: f62bb382d964be9661df3bd51aacaec05299dea9

    - name: Install zram-swap-config
      ansible.builtin.command:
        cmd: sh install.sh
        chdir: /tmp/zram-swap-config/
        creates: /etc/zram-swap-config.conf

    - name: Configure zram swap
      ansible.builtin.copy:
        dest: /etc/zram-swap-config.conf
        content: |
          MEM_FACTOR=25
          DRIVE_FACTOR=300
          COMP_ALG=lz4
          SWAP_DEVICES=1
          SWAP_PRI=75
          PAGE_CLUSTER=0
          SWAPPINESS=80
        mode: 0644
      notify:
        - Reboot server

    - name: Configure to use swap sooner
      ansible.builtin.blockinfile:
        path: /etc/sysctl.conf
        block: |
          vm.vfs_cache_pressure=500
          vm.swappiness=100
          vm.dirty_background_ratio=1
          vm.dirty_ratio=50


    - name: Force all notified handlers to run
      ansible.builtin.meta: flush_handlers

  handlers:
    - name: Reboot server
      ansible.builtin.command: reboot
      async: 100
      poll: 0
      changed_when: false

    - name: Wait 600 seconds, but only start checking after 10 seconds
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 600

- name: Prepare monitor
  hosts: ceph-mon1
  become: true

  roles:

    - role: einfachit.hpc.ceph_bootstrap
