---

- name: Install needed packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - dnsmasq
    - iptables-persistent


- name: Configure static IP for eth0
  community.general.nmcli:
    conn_name: eth0
    type: ethernet
    ip4: "{{ wifi_bridge_eth0_ip }}/24"
    state: present
  notify:
    - Reapply eth0 config

- name: Configure dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^no-dhcp-interface="
      line: "no-dhcp-interface=wlan0"
    - regexp: "^dhcp-range="
      line: "dhcp-range={{ wifi_bridge_dhcp_range }}"
    - regexp: "^bogus-priv"
      line: "bogus-priv"
    - regexp: "^domain-needed"
      line: "domain-needed"
  notify: Setup dnsmasq service

- name: Add localhost dns
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhclient.conf
    regexp: "^#prepend domain-name-servers 127.0.0.1;"
    line: prepend domain-name-servers 127.0.0.1;
  notify: Renew dhcp lease

- name: Configure ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: setup iptables
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: wlan0
    jump: "MASQUERADE"
  notify: Persist iptables


- name: setup iptables 
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: wlan0
    out_interface: eth0
    ctstate: ESTABLISHED,RELATED
    jump: "ACCEPT"
  notify: Persist iptables

- name: setup iptables 
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: eth0
    out_interface: wlan0
    jump: "ACCEPT"
  notify: Persist iptables
