---

- name: Install needed packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - dnsmasq
    - iptables-persistent


- name: Configure static IP for lan device
  community.general.nmcli:
    conn_name: "{{ wifi_bridge_lan_dev }}"
    type: ethernet
    ip4: "{{ wifi_bridge_lan_ip }}/24"
    state: present
  notify:
    - Reapply lan config

- name: Configure dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^no-dhcp-interface="
      line: "no-dhcp-interface={{ wifi_bridge_external_dev }}"
    - regexp: "^dhcp-range="
      line: "dhcp-range={{ wifi_bridge_dhcp_range }}"
    - regexp: "^bogus-priv"
      line: "bogus-priv"
    - regexp: "^domain-needed"
      line: "domain-needed"
  notify: Restart dnsmasq service

- name: Add localhost dns
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhclient.conf
    regexp: "^#prepend domain-name-servers 127.0.0.1;"
    line: prepend domain-name-servers 127.0.0.1;
  notify: Renew dhcp lease

- name: Configure ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: setup iptables
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ wifi_bridge_external_dev }}"
    jump: "MASQUERADE"
  notify: Persist iptables


- name: setup iptables 
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: "{{ wifi_bridge_external_dev }}"
    out_interface: "{{ wifi_bridge_lan_dev }}"
    ctstate: ESTABLISHED,RELATED
    jump: "ACCEPT"
  notify: Persist iptables

- name: setup iptables 
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: "{{ wifi_bridge_lan_dev }}"
    out_interface: "{{ wifi_bridge_external_dev }}"
    jump: "ACCEPT"
  notify: Persist iptables

- name: Start dnsmasq service
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
