---

- name: Restart mini-httpd
  ansible.builtin.service:
    name: mini-httpd
    state: restarted
    enabled: true

- name: Restart traefik
  docker_container:
    name: traefik
    state: started
    restart: yes
