---
- name: Configure netboot server
  hosts: netboot_server
  become: true
  gather_facts: true
  tasks:

  - name: Setup netboot server
    include_role:
      name: "einfachit.piaas.netboot_server"

  - name: Setup netboot server
    include_role:
      name: "einfachit.piaas.wifi_bridge"


  - name: Setup piaas service
    include_role:
      name: "einfachit.piaas.webui"
