---
dependency:
  name: galaxy
prerun: false
driver:
  name: default
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: mighty-mouse
    groups:
      - raspberries
      - netboot_server
provisioner:
  name: ansible
  inventory:
    host_vars:
      mighty-mouse:
        raw_hostname: 'raspberrypi'  # rpi4 4GB
        hostname: mighty-mouse
        ansible_host: "{{ hostname }}.local"
        ansible_user: epic 
        ansible_ssh_common_args: |
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
        ansible_python_interpreter: /usr/bin/python3
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
scenario:
  name: int
  converge_sequence:
    - converge
verifier:
  name: ansible
