---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: os-controller1
    groups:
      - raspberries
      - os
  - name: docker-registry
    groups:
      - container
  - name: kolla-builder
    groups:
      - container
  - name: docker-host
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/
  inventory:
    host_vars:
      os-controller1:
        raw_hostname: '0x54a2adca'
        hostname: os-controller1
        ansible_host: "{{ hostname }}.local"
        ansible_user: pi
        ansible_ssh_pass: raspberry
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        ansible_python_interpreter: /usr/bin/python3
      docker-registry:
        image: "registry:2"
        ports:
          - "5000:5000"
        command: []
      kolla-builder:
        image: "ubuntu:focal"
        ports: []
        command: ["sleep", "infinity"]
      docker-host:
        hostname: docker-horst
        ansible_host: "{{ hostname }}.local"
        ansible_user: pi
        ansible_ssh_pass: raspberry
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        ansible_python_interpreter: /usr/bin/python3
    group_vars:
      container:
        ansible_connection: docker
        docker_keep_volumes: true # do not delete home directories when deleting container
        docker_api_host: "docker-horst.local"
        docker_host: "tcp://{{ docker_api_host }}:2375"
        ansible_python_interpreter: /usr/bin/python3

scenario:
  name: int
  converge_sequence:
    - dependency
    - converge
verifier:
  name: ansible
