---
- hosts: container
  gather_facts: false
  connection: local
  tasks:

  - name: Wait for docker api to get available
    wait_for:
      port: 2375
      host: "{{ docker_host }}"
      # search_regex: Connected
    vars:
      ansible_connection: local
    delegate_to: localhost

  - name: Start registry container
    docker_container:
      name: "docker-registry"
      image: "registry:2"
      restart_policy: always
      published_ports: 5000:5000
      docker_host: "tcp://{{ docker_host }}:2375"
      # container_default_behavior: no_defaults
    delegate_to: localhost
