---
- name: Provision container
  hosts: container
  gather_facts: false
  connection: local
  tasks:

  - name: Wait for docker api to get available
    ansible.builtin.wait_for:
      port: 2375
      host: "{{ docker_api_host }}"
      # search_regex: Connected
    vars:
      ansible_connection: local
    delegate_to: localhost
    run_once: true

  - name: Start container
    ansible.builtin.docker_container:
      name: "{{ inventory_hostname }}"
      image: "{{ image }}"
      command: "{{ command }}"
      command_handling: compatibility
      restart: false
      restart_policy: unless-stopped
      state: started
      docker_host: "tcp://{{ docker_api_host }}:2375"
      published_ports: "{{ ports }}"
      container_default_behavior: no_defaults
    delegate_to: localhost

- name: Prepare kolla build container
  hosts: kolla-builder
  gather_facts: false
  connection: docker
  vars:
    docker_host: docker-host
    docker_api: "tcp://{{ hostvars[docker_host].ansible_host }}:2375"
    ansible_docker_extra_args: "-H={{ docker_api }}"

  tasks:

    - name: Install python3
      community.docker.docker_container_exec:
        container: "{{ inventory_hostname }}"
        docker_host: "tcp://{{ docker_api_host }}:2375"
        command: /bin/bash -c "apt update; apt -y install python3"
        chdir: /root
      register: result
      delegate_to: localhost

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - git
          - libffi-dev
          - gcc
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-venv

    - name: Install and upgrade pip
      ansible.builtin.pip:
        name: pip
        extra_args: --upgrade

    - name: Build python3 virtual environment
      ansible.builtin.pip:
        name: kolla==14.6.0
        virtualenv: /opt/kolla-ansible/venv/
        virtualenv_command: python3 -m venv

    - name: Install kolla
      ansible.builtin.pip:
        name: 'kolla'

    - name: Bugfix Dockerfiles for aarch64
      ansible.builtin.blockinfile:
        path: /opt/kolla-ansible/venv/share/kolla/docker/kolla-toolbox/Dockerfile.j2
        block: |
          RUN echo 'deb https://packages.erlang-solutions.com/ubuntu focal contrib' | sudo tee -a /etc/apt/sources.list \
              && curl -o erlang_solutions.asc  https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc \
              && sudo apt-key add erlang_solutions.asc
        insertbefore: ^.*macros.enable_extra_repos.*erlang.*openvswitch.*powertools.*rabbitmq.*$

    - name: Build kolla arm container images
      ansible.builtin.shell:
        cmd: |
          source /opt/kolla-ansible/venv/bin/activate && \
          export DOCKER_HOST="tcp://172.17.0.1:2375" &&  \
          kolla-build -b ubuntu --type binary --skip-existing --registry docker-horst.local:5000 --push
        executable: /bin/bash
        creates: ttt
      async: 20800
      poll: 30
